// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NubArca.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NubArca.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530092502_AddAlbums")]
    partial class AddAlbums
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NubArca.Api.Domain.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_albums_owner_name");

                    b.ToTable("albums", (string)null);
                });

            modelBuilder.Entity("NubArca.Api.Domain.AlbumItem", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FileItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AlbumId", "FileItemId");

                    b.HasIndex("FileItemId");

                    b.ToTable("album_items", (string)null);
                });

            modelBuilder.Entity("NubArca.Api.Domain.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Action", "CreatedAt")
                        .HasDatabaseName("ix_audit_logs_action_created");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_audit_logs_user_created");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("NubArca.Api.Domain.BlobMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlobObjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("BodySerialNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CameraMake")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CameraModel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ColorSpace")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTaken")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DateTakenOffset")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("DateTakenSource")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DetectedContentType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DetectedFormat")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ExposureBias")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ExposureProgram")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ExposureTime")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("ExtractedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtractionErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExtractionStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("ExtractionVersion")
                        .HasColumnType("integer");

                    b.Property<double?>("FNumber")
                        .HasColumnType("double precision");

                    b.Property<string>("Flash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double?>("FocalLength")
                        .HasColumnType("double precision");

                    b.Property<int?>("FocalLength35mm")
                        .HasColumnType("integer");

                    b.Property<double?>("GpsAltitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("GpsLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("GpsLongitude")
                        .HasColumnType("double precision");

                    b.Property<bool>("HasIccProfile")
                        .HasColumnType("boolean");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("IccProfileName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("IsoSpeed")
                        .HasColumnType("integer");

                    b.Property<string>("LensMake")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LensModel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LensSerialNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("MediaCategory")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MeteringMode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("Orientation")
                        .HasColumnType("integer");

                    b.Property<long?>("PixelCount")
                        .HasColumnType("bigint");

                    b.Property<string>("RawMetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Software")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ThumbnailStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WhiteBalance")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BlobObjectId")
                        .IsUnique()
                        .HasDatabaseName("ux_blob_metadata_blob_object");

                    b.ToTable("blob_metadata", null, t =>
                        {
                            t.HasCheckConstraint("ck_blob_metadata_height_positive", "\"Height\" IS NULL OR \"Height\" > 0");

                            t.HasCheckConstraint("ck_blob_metadata_pixel_count_non_negative", "\"PixelCount\" IS NULL OR \"PixelCount\" >= 0");

                            t.HasCheckConstraint("ck_blob_metadata_size_bytes_non_negative", "\"SizeBytes\" >= 0");

                            t.HasCheckConstraint("ck_blob_metadata_width_positive", "\"Width\" IS NULL OR \"Width\" > 0");
                        });
                });

            modelBuilder.Entity("NubArca.Api.Domain.BlobObject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ReferenceCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .IsUnique()
                        .HasDatabaseName("ux_blob_objects_sha256");

                    b.ToTable("blob_objects", null, t =>
                        {
                            t.HasCheckConstraint("ck_blob_objects_reference_count_non_negative", "\"ReferenceCount\" >= 0");

                            t.HasCheckConstraint("ck_blob_objects_size_bytes_non_negative", "\"SizeBytes\" >= 0");
                        });
                });

            modelBuilder.Entity("NubArca.Api.Domain.FileItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlobObjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BlobObjectId")
                        .HasDatabaseName("ix_file_items_blob_object");

                    b.HasIndex("ParentFolderId");

                    b.HasIndex("OwnerUserId", "Name")
                        .HasDatabaseName("ix_file_items_owner_name");

                    b.HasIndex("OwnerUserId", "ParentFolderId", "DeletedAt")
                        .HasDatabaseName("ix_file_items_owner_parent_deleted");

                    b.HasIndex("OwnerUserId", "ParentFolderId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_file_items_active_sibling_name")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("OwnerUserId", "ParentFolderId", "Name"), false);

                    b.HasIndex("OwnerUserId", "DeletedAt", "CreatedAt", "Id")
                        .HasDatabaseName("ix_file_items_owner_deleted_created_id");

                    b.HasIndex("OwnerUserId", "DeletedAt", "SizeBytes", "Id")
                        .HasDatabaseName("ix_file_items_owner_deleted_size_id");

                    b.ToTable("file_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_file_items_size_bytes_non_negative", "\"SizeBytes\" >= 0");
                        });
                });

            modelBuilder.Entity("NubArca.Api.Domain.FileItemUserMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTakenOverride")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("FileItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<string>("LocationOverride")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("TagsJson")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileItemId")
                        .IsUnique()
                        .HasDatabaseName("ux_file_item_user_metadata_file");

                    b.ToTable("file_item_user_metadata", null, t =>
                        {
                            t.HasCheckConstraint("ck_file_item_user_metadata_rating_range", "\"Rating\" IS NULL OR (\"Rating\" >= 0 AND \"Rating\" <= 5)");
                        });
                });

            modelBuilder.Entity("NubArca.Api.Domain.FileThumbnail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlobObjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FileItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BlobObjectId")
                        .HasDatabaseName("ix_file_thumbnails_blob_object");

                    b.HasIndex("FileItemId", "Size")
                        .IsUnique()
                        .HasDatabaseName("ux_file_thumbnails_file_size");

                    b.ToTable("file_thumbnails", null, t =>
                        {
                            t.HasCheckConstraint("ck_file_thumbnails_height_positive", "\"Height\" > 0");

                            t.HasCheckConstraint("ck_file_thumbnails_width_positive", "\"Width\" > 0");
                        });
                });

            modelBuilder.Entity("NubArca.Api.Domain.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId");

                    b.HasIndex("OwnerUserId", "ParentFolderId", "DeletedAt")
                        .HasDatabaseName("ix_folders_owner_parent_deleted");

                    b.HasIndex("OwnerUserId", "ParentFolderId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_folders_active_sibling_name")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("OwnerUserId", "ParentFolderId", "Name"), false);

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("NubArca.Api.Domain.ShareLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DownloadCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FileItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxDownloads")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("FileItemId")
                        .HasDatabaseName("ix_share_links_file_item");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_share_links_owner");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_share_links_token_hash");

                    b.ToTable("share_links", null, t =>
                        {
                            t.HasCheckConstraint("ck_share_links_download_count_non_negative", "\"DownloadCount\" >= 0");

                            t.HasCheckConstraint("ck_share_links_max_downloads_positive_or_null", "\"MaxDownloads\" IS NULL OR \"MaxDownloads\" > 0");
                        });
                });

            modelBuilder.Entity("NubArca.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("NubArca.Api.Domain.Album", b =>
                {
                    b.HasOne("NubArca.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NubArca.Api.Domain.AlbumItem", b =>
                {
                    b.HasOne("NubArca.Api.Domain.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NubArca.Api.Domain.FileItem", null)
                        .WithMany()
                        .HasForeignKey("FileItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NubArca.Api.Domain.AuditLog", b =>
                {
                    b.HasOne("NubArca.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NubArca.Api.Domain.BlobMetadata", b =>
                {
                    b.HasOne("NubArca.Api.Domain.BlobObject", null)
                        .WithMany()
                        .HasForeignKey("BlobObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NubArca.Api.Domain.FileItem", b =>
                {
                    b.HasOne("NubArca.Api.Domain.BlobObject", null)
                        .WithMany()
                        .HasForeignKey("BlobObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NubArca.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NubArca.Api.Domain.Folder", null)
                        .WithMany()
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NubArca.Api.Domain.FileItemUserMetadata", b =>
                {
                    b.HasOne("NubArca.Api.Domain.FileItem", null)
                        .WithMany()
                        .HasForeignKey("FileItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NubArca.Api.Domain.FileThumbnail", b =>
                {
                    b.HasOne("NubArca.Api.Domain.BlobObject", null)
                        .WithMany()
                        .HasForeignKey("BlobObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NubArca.Api.Domain.FileItem", null)
                        .WithMany()
                        .HasForeignKey("FileItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NubArca.Api.Domain.Folder", b =>
                {
                    b.HasOne("NubArca.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NubArca.Api.Domain.Folder", null)
                        .WithMany()
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NubArca.Api.Domain.ShareLink", b =>
                {
                    b.HasOne("NubArca.Api.Domain.FileItem", null)
                        .WithMany()
                        .HasForeignKey("FileItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NubArca.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
