// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NubArca.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NubArca.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610080059_AddRemoteUploadStaging")]
    partial class AddRemoteUploadStaging
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NubArca.Api.Domain.AdminImportItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConflictCategory")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureCategory")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("FileItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("SourceModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_admin_import_items_run_ordinal");

                    b.HasIndex("ImportRunId", "Status")
                        .HasDatabaseName("ix_admin_import_items_run_status");

                    b.ToTable("admin_import_items", (string)null);
                });

            modelBuilder.Entity("NubArca.Api.Domain.AdminImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("AlreadyImportedFiles")
                        .HasColumnType("integer");

                    b.Property<long?>("BlobDbMillis")
                        .HasColumnType("bigint");

                    b.Property<int>("CancelledFiles")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ConflictFiles")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentRelativePath")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<Guid?>("DestinationFolderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("FailedFiles")
                        .HasColumnType("integer");

                    b.Property<long?>("FileItemMillis")
                        .HasColumnType("bigint");

                    b.Property<long?>("FolderMillis")
                        .HasColumnType("bigint");

                    b.Property<long?>("HashMillis")
                        .HasColumnType("bigint");

                    b.Property<long>("ImportedBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("ImportedFiles")
                        .HasColumnType("integer");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid");

                    b.Property<long?>("MetadataMillis")
                        .HasColumnType("bigint");

                    b.Property<string>("Phase")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long?>("ReadMillis")
                        .HasColumnType("bigint");

                    b.Property<string>("RootId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("ScanCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ScannedFiles")
                        .HasColumnType("integer");

                    b.Property<int>("SkippedFiles")
                        .HasColumnType("integer");

                    b.Property<string>("SourceRelativePath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<Guid?>("StagingSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid");

                    b.Property<long?>("ThumbnailMillis")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalDirectories")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("WriteMillis")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_admin_import_runs_created_desc");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_admin_import_runs_job");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("ix_admin_import_runs_target_user");

                    b.ToTable("admin_import_runs", (string)null);
                });

            modelBuilder.Entity("NubArca.Api.Domain.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_albums_owner_name");

                    b.ToTable("albums", (string)null);
                });

            modelBuilder.Entity("NubArca.Api.Domain.AlbumItem", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FileItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AlbumId", "FileItemId");

                    b.HasIndex("FileItemId");

                    b.ToTable("album_items", (string)null);
                });

            modelBuilder.Entity("NubArca.Api.Domain.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Action", "CreatedAt")
                        .HasDatabaseName("ix_audit_logs_action_created");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_audit_logs_user_created");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("NubArca.Api.Domain.BackgroundJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AvailableAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CancellationRequested")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LockOwner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int?>("ProgressCurrent")
                        .HasColumnType("integer");

                    b.Property<string>("ProgressMessage")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ProgressTotal")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_background_jobs_idempotency");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_background_jobs_type");

                    b.HasIndex("Status", "AvailableAt")
                        .HasDatabaseName("ix_background_jobs_status_available");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_background_jobs_status_created");

                    b.ToTable("background_jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_background_jobs_attempts_nonneg", "\"Attempts\" >= 0 AND \"MaxAttempts\" >= 1");
                        });
                });

            modelBuilder.Entity("NubArca.Api.Domain.BlobMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlobObjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("BodySerialNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CameraMake")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CameraModel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ColorSpace")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTaken")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DateTakenOffset")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("DateTakenSource")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DetectedContentType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DetectedFormat")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ExposureBias")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ExposureProgram")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ExposureTime")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("ExtractedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtractionErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExtractionStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("ExtractionVersion")
                        .HasColumnType("integer");

                    b.Property<double?>("FNumber")
                        .HasColumnType("double precision");

                    b.Property<string>("Flash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double?>("FocalLength")
                        .HasColumnType("double precision");

                    b.Property<int?>("FocalLength35mm")
                        .HasColumnType("integer");

                    b.Property<double?>("GpsAltitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("GpsLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("GpsLongitude")
                        .HasColumnType("double precision");

                    b.Property<bool>("HasIccProfile")
                        .HasColumnType("boolean");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("IccProfileName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("IsoSpeed")
                        .HasColumnType("integer");

                    b.Property<string>("LensMake")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LensModel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LensSerialNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("MediaCategory")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MeteringMode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("Orientation")
                        .HasColumnType("integer");

                    b.Property<long?>("PixelCount")
                        .HasColumnType("bigint");

                    b.Property<string>("RawMetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Software")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ThumbnailStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WhiteBalance")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BlobObjectId")
                        .IsUnique()
                        .HasDatabaseName("ux_blob_metadata_blob_object");

                    b.ToTable("blob_metadata", null, t =>
                        {
                            t.HasCheckConstraint("ck_blob_metadata_height_positive", "\"Height\" IS NULL OR \"Height\" > 0");

                            t.HasCheckConstraint("ck_blob_metadata_pixel_count_non_negative", "\"PixelCount\" IS NULL OR \"PixelCount\" >= 0");

                            t.HasCheckConstraint("ck_blob_metadata_size_bytes_non_negative", "\"SizeBytes\" >= 0");

                            t.HasCheckConstraint("ck_blob_metadata_width_positive", "\"Width\" IS NULL OR \"Width\" > 0");
                        });
                });

            modelBuilder.Entity("NubArca.Api.Domain.BlobObject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ReferenceCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .IsUnique()
                        .HasDatabaseName("ux_blob_objects_sha256");

                    b.ToTable("blob_objects", null, t =>
                        {
                            t.HasCheckConstraint("ck_blob_objects_reference_count_non_negative", "\"ReferenceCount\" >= 0");

                            t.HasCheckConstraint("ck_blob_objects_size_bytes_non_negative", "\"SizeBytes\" >= 0");
                        });
                });

            modelBuilder.Entity("NubArca.Api.Domain.FileItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlobObjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EffectiveDateTaken")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EffectiveDateTakenSource")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BlobObjectId")
                        .HasDatabaseName("ix_file_items_blob_object");

                    b.HasIndex("ParentFolderId");

                    b.HasIndex("OwnerUserId", "Name")
                        .HasDatabaseName("ix_file_items_owner_name");

                    b.HasIndex("OwnerUserId", "EffectiveDateTaken", "Id")
                        .HasDatabaseName("ix_file_items_owner_deleted_effdate_id")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("OwnerUserId", "ParentFolderId", "DeletedAt")
                        .HasDatabaseName("ix_file_items_owner_parent_deleted");

                    b.HasIndex("OwnerUserId", "ParentFolderId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_file_items_active_sibling_name")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("OwnerUserId", "ParentFolderId", "Name"), false);

                    b.HasIndex("OwnerUserId", "DeletedAt", "CreatedAt", "Id")
                        .HasDatabaseName("ix_file_items_owner_deleted_created_id");

                    b.HasIndex("OwnerUserId", "DeletedAt", "SizeBytes", "Id")
                        .HasDatabaseName("ix_file_items_owner_deleted_size_id");

                    b.ToTable("file_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_file_items_size_bytes_non_negative", "\"SizeBytes\" >= 0");
                        });
                });

            modelBuilder.Entity("NubArca.Api.Domain.FileItemUserMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTakenOverride")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("FileItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<string>("LocationOverride")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("TagsJson")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileItemId")
                        .IsUnique()
                        .HasDatabaseName("ux_file_item_user_metadata_file");

                    b.ToTable("file_item_user_metadata", null, t =>
                        {
                            t.HasCheckConstraint("ck_file_item_user_metadata_rating_range", "\"Rating\" IS NULL OR (\"Rating\" >= 0 AND \"Rating\" <= 5)");
                        });
                });

            modelBuilder.Entity("NubArca.Api.Domain.FileThumbnail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlobObjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FileItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BlobObjectId")
                        .HasDatabaseName("ix_file_thumbnails_blob_object");

                    b.HasIndex("FileItemId", "Size")
                        .IsUnique()
                        .HasDatabaseName("ux_file_thumbnails_file_size");

                    b.ToTable("file_thumbnails", null, t =>
                        {
                            t.HasCheckConstraint("ck_file_thumbnails_height_positive", "\"Height\" > 0");

                            t.HasCheckConstraint("ck_file_thumbnails_width_positive", "\"Width\" > 0");
                        });
                });

            modelBuilder.Entity("NubArca.Api.Domain.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId");

                    b.HasIndex("OwnerUserId", "ParentFolderId", "DeletedAt")
                        .HasDatabaseName("ix_folders_owner_parent_deleted");

                    b.HasIndex("OwnerUserId", "ParentFolderId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_folders_active_sibling_name")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("OwnerUserId", "ParentFolderId", "Name"), false);

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("NubArca.Api.Domain.RemoteUploadChunk", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("integer");

                    b.HasKey("ItemId", "ChunkIndex");

                    b.ToTable("remote_upload_chunks", (string)null);
                });

            modelBuilder.Entity("NubArca.Api.Domain.RemoteUploadItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkSizeBytes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExpectedChunkCount")
                        .HasColumnType("integer");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<long>("ReceivedBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("ReceivedChunkCount")
                        .HasColumnType("integer");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_remote_upload_items_session_ordinal");

                    b.HasIndex("SessionId", "Status")
                        .HasDatabaseName("ix_remote_upload_items_session_status");

                    b.ToTable("remote_upload_items", (string)null);
                });

            modelBuilder.Entity("NubArca.Api.Domain.RemoteUploadSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdminImportRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DestinationFolderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedFiles")
                        .HasColumnType("integer");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("ReceivedBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("ReceivedFiles")
                        .HasColumnType("integer");

                    b.Property<string>("StagingRelativeRoot")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalFiles")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VerifiedFiles")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_remote_upload_sessions_expires");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_remote_upload_sessions_status");

                    b.HasIndex("CreatedByUserId", "CreatedAt")
                        .HasDatabaseName("ix_remote_upload_sessions_owner_created");

                    b.ToTable("remote_upload_sessions", (string)null);
                });

            modelBuilder.Entity("NubArca.Api.Domain.ShareLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DownloadCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FileItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxDownloads")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("FileItemId")
                        .HasDatabaseName("ix_share_links_file_item");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_share_links_owner");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_share_links_token_hash");

                    b.ToTable("share_links", null, t =>
                        {
                            t.HasCheckConstraint("ck_share_links_download_count_non_negative", "\"DownloadCount\" >= 0");

                            t.HasCheckConstraint("ck_share_links_max_downloads_positive_or_null", "\"MaxDownloads\" IS NULL OR \"MaxDownloads\" > 0");
                        });
                });

            modelBuilder.Entity("NubArca.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("NubArca.Api.Domain.AdminImportItem", b =>
                {
                    b.HasOne("NubArca.Api.Domain.AdminImportRun", null)
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NubArca.Api.Domain.Album", b =>
                {
                    b.HasOne("NubArca.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NubArca.Api.Domain.AlbumItem", b =>
                {
                    b.HasOne("NubArca.Api.Domain.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NubArca.Api.Domain.FileItem", null)
                        .WithMany()
                        .HasForeignKey("FileItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NubArca.Api.Domain.AuditLog", b =>
                {
                    b.HasOne("NubArca.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NubArca.Api.Domain.BlobMetadata", b =>
                {
                    b.HasOne("NubArca.Api.Domain.BlobObject", null)
                        .WithMany()
                        .HasForeignKey("BlobObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NubArca.Api.Domain.FileItem", b =>
                {
                    b.HasOne("NubArca.Api.Domain.BlobObject", null)
                        .WithMany()
                        .HasForeignKey("BlobObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NubArca.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NubArca.Api.Domain.Folder", null)
                        .WithMany()
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NubArca.Api.Domain.FileItemUserMetadata", b =>
                {
                    b.HasOne("NubArca.Api.Domain.FileItem", null)
                        .WithMany()
                        .HasForeignKey("FileItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NubArca.Api.Domain.FileThumbnail", b =>
                {
                    b.HasOne("NubArca.Api.Domain.BlobObject", null)
                        .WithMany()
                        .HasForeignKey("BlobObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NubArca.Api.Domain.FileItem", null)
                        .WithMany()
                        .HasForeignKey("FileItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NubArca.Api.Domain.Folder", b =>
                {
                    b.HasOne("NubArca.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NubArca.Api.Domain.Folder", null)
                        .WithMany()
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NubArca.Api.Domain.RemoteUploadChunk", b =>
                {
                    b.HasOne("NubArca.Api.Domain.RemoteUploadItem", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NubArca.Api.Domain.RemoteUploadItem", b =>
                {
                    b.HasOne("NubArca.Api.Domain.RemoteUploadSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NubArca.Api.Domain.ShareLink", b =>
                {
                    b.HasOne("NubArca.Api.Domain.FileItem", null)
                        .WithMany()
                        .HasForeignKey("FileItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NubArca.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
