using NubArca.Api.Domain;
using NubArca.Api.Folders;

namespace NubArca.Api.Files;

public interface IFileItemService
{
    Task<FileItem> CreateAsync(
        Guid ownerUserId,
        Guid? parentFolderId,
        string name,
        string? mimeType,
        Stream content,
        CancellationToken cancellationToken = default,
        // Slice 82: when supplied (admin import only), per-phase timings are
        // accumulated into it. Null on every normal upload — no timing work.
        FileCreateTimings? timings = null,
        // Slice 92: false (admin import default) skips the inline small image
        // thumbnail — derivatives are generated by a background job or lazily
        // on first request instead. Browser uploads keep the eager default.
        bool generateSmallThumbnail = true,
        // Slice 94: false (admin/staging import default) writes only the cheap
        // detection facts inline and defers full embedded EXIF/IPTC/XMP/GPS
        // extraction to the asynchronous metadata.embedded.backfill job.
        // Browser uploads keep the inline default.
        bool extractEmbeddedMetadata = true);

    Task<FileItem?> GetByIdAsync(
        Guid fileItemId,
        Guid ownerUserId,
        CancellationToken cancellationToken = default);

    Task<FileContent?> OpenContentAsync(
        Guid fileItemId,
        Guid ownerUserId,
        CancellationToken cancellationToken = default);

    Task<IReadOnlyList<FileSummary>> ListChildrenAsync(
        Guid ownerUserId,
        Guid? parentFolderId,
        CancellationToken cancellationToken = default);

    // Files UI v2: one seek-paginated page of a folder's files, ordered by the
    // requested directory sort. `cursor` resumes a prior page (already validated
    // for sort/direction/scope by the endpoint). Fetches limit+1 internally to
    // report HasMore without a COUNT(*).
    Task<DirectoryFilesPage> ListChildFilesPageAsync(
        Guid ownerUserId,
        Guid? parentFolderId,
        DirectorySortField sort,
        DirectorySortDirection direction,
        int limit,
        DirectoryCursor? cursor,
        CancellationToken cancellationToken = default);

    // Returns soft-deleted FileItem rows for this owner, optionally filtered
    // to a specific parent folder. Ordered by DeletedAt desc, then Name asc
    // for deterministic output. Never returns active rows, foreign rows, or
    // hard-purged rows.
    Task<IReadOnlyList<FileTrashSummary>> ListTrashAsync(
        Guid ownerUserId,
        Guid? parentFolderId = null,
        CancellationToken cancellationToken = default);

    Task<IReadOnlyList<FileSummary>> SearchAsync(
        Guid ownerUserId,
        string query,
        CancellationToken cancellationToken = default);

    // Returns a single page of active image FileItems for the gallery view.
    // Filters by MIME type prefix "image/" so files whose dimension detection
    // failed at upload still appear (their thumbnail URL may 404). Limit is
    // expected to already be clamped by the caller to a sane range.
    // When `nameQuery` is non-null and non-whitespace, results are further
    // filtered by case-insensitive substring match on Name. Whitespace queries
    // are treated as "no filter" — the caller should also strip them.
    // Ordering: primary by `sort` in `direction`, secondary deterministic
    // tiebreaker by Id ascending. Defaults are Created+Desc.
    Task<IReadOnlyList<ImageItem>> ListImagesAsync(
        Guid ownerUserId,
        Guid? parentFolderId,
        int limit,
        int offset,
        string? nameQuery = null,
        ImageSortField sort = ImageSortField.Created,
        ImageSortDirection direction = ImageSortDirection.Desc,
        CancellationToken cancellationToken = default);

    // Slice 60: cursor pagination. When `cursor` is null, returns the first
    // page. When non-null, the cursor's `Sort`/`Direction` must match the
    // arguments (the endpoint validates this; this method trusts the caller).
    // Returns up to `limit` items plus a `NextCursor` when more results
    // exist. No COUNT(*) is run — `HasMore` is derived from a `limit + 1`
    // fetch. Owner-scoped, gallery-membership rule identical to ListImagesAsync.
    //
    // Slice 61: `filters` carries the q expansion (name/title/description/
    // tags) + favorite / minRating / hasGps / dateTakenFrom / dateTakenTo /
    // folderId. The fingerprint of `filters` is also embedded into the
    // returned `NextCursor` so a follow-up request with a different filter
    // set can be rejected by the endpoint (no silent boundary leakage).
    Task<ImagePage> ListImagesPageAsync(
        Guid ownerUserId,
        int limit,
        ImageCursor? cursor,
        ImageFilters filters,
        ImageSortField sort = ImageSortField.Created,
        ImageSortDirection direction = ImageSortDirection.Desc,
        CancellationToken cancellationToken = default);

    // Hydrates an already-ranked owner-private set (semantic retrieval) into
    // normal gallery DTOs while preserving the supplied relevance order.
    Task<IReadOnlyList<ImageItem>> ListGalleryImagesByRankAsync(
        Guid ownerUserId,
        IReadOnlyList<Guid> rankedFileItemIds,
        CancellationToken cancellationToken = default);

    // Physical-filter-first candidate set for semantic ranking: up to `cap`
    // (Id, BlobObjectId) pairs matching the PHYSICAL projection of the filters
    // (semantic residual removed), through the same shared gallery query, with
    // the text-search-only small-image quality gate applied afterwards.
    // SEARCH-SEM-01: `afterId` keyset-pages the eligible set so semantic
    // ranking can cover the whole library in bounded batches instead of a
    // GUID-ordered prefix. Omitting it preserves the original behaviour.
    Task<IReadOnlyList<GalleryCandidateRef>> ListPhysicalGalleryCandidatesAsync(
        Guid ownerUserId,
        ImageFilters filters,
        int cap,
        CancellationToken cancellationToken = default,
        Guid? afterId = null);

    // VSEM-03: video counterpart of ListPhysicalGalleryCandidatesAsync — the
    // physically filtered, owner-visible video candidate set for unified
    // semantic ranking. Same shared gallery query; no photo quality gate.
    // SEARCH-SEM-01: `afterId` keyset-pages the eligible set so semantic
    // ranking can cover the whole library in bounded batches instead of a
    // GUID-ordered prefix. Omitting it preserves the original behaviour.
    Task<IReadOnlyList<GalleryCandidateRef>> ListPhysicalVideoCandidatesAsync(
        Guid ownerUserId,
        ImageFilters filters,
        int cap,
        CancellationToken cancellationToken = default,
        Guid? afterId = null);

    // VSEM-03: hydrates an already-ranked owner-private MIXED media set into
    // unified MediaItem DTOs preserving the supplied relevance order (the
    // media counterpart of ListGalleryImagesByRankAsync).
    Task<IReadOnlyList<MediaItem>> ListGalleryMediaByRankAsync(
        Guid ownerUserId,
        IReadOnlyList<Guid> rankedFileItemIds,
        CancellationToken cancellationToken = default);

    // Count of physically filtered candidates that also have an embedding for
    // the given profile (denominator base before Top-K reduction).
    Task<int> CountEmbeddedGalleryCandidatesAsync(
        Guid ownerUserId,
        ImageFilters filters,
        Guid profileId,
        CancellationToken cancellationToken = default);

    // True when the file is currently ELIGIBLE for the owner's image gallery —
    // the exact membership rule of ListImagesPageAsync with empty filters
    // (owner-owned, active, server-detected image, media-library visible,
    // vault excluded by the global filter). Used by per-item authorization on
    // gallery projections (e.g. TV personal media bytes) so an id that the
    // gallery would never list cannot be fetched directly.
    Task<bool> IsGalleryImageAsync(
        Guid ownerUserId,
        Guid fileItemId,
        CancellationToken cancellationToken = default);

    // Same exact membership gate for the owner video gallery. Used by TV
    // personal-video JSON and byte endpoints so direct ids cannot bypass the
    // media-library / vault / ownership filters.
    Task<bool> IsGalleryVideoAsync(
        Guid ownerUserId,
        Guid fileItemId,
        CancellationToken cancellationToken = default);

    // Slice 86: cursor-paginated video gallery. Same machinery as
    // ListImagesPageAsync but membership is server-detected `video/*` and items
    // carry the poster URL. Owner-scoped + soft-delete-aware + no-leak.
    Task<VideoPage> ListVideosPageAsync(
        Guid ownerUserId,
        int limit,
        ImageCursor? cursor,
        ImageFilters filters,
        ImageSortField sort = ImageSortField.Created,
        ImageSortDirection direction = ImageSortDirection.Desc,
        CancellationToken cancellationToken = default);

    // Slice 5: unified media page for the "Tutti | Foto | Video" workspace.
    // Same cursor/sort/filter/scope machinery as the photo & video galleries;
    // `kind` selects images, videos, or both. Projects a discriminated MediaItem
    // and returns per-kind counts. Owner-scoped + soft-delete-aware + no-leak.
    Task<MediaPage> ListMediaPageAsync(
        Guid ownerUserId,
        int limit,
        ImageCursor? cursor,
        ImageFilters filters,
        MediaKindScope kind,
        ImageSortField sort = ImageSortField.Created,
        ImageSortDirection direction = ImageSortDirection.Desc,
        CancellationToken cancellationToken = default);

    // Distinct video codecs across the owner's active videos (video-gallery
    // codec filter facet). Owner-scoped; lower-cased short names, sorted.
    Task<IReadOnlyList<string>> ListVideoCodecsAsync(
        Guid ownerUserId, CancellationToken cancellationToken = default);

    Task<FileItem?> RenameAsync(
        Guid ownerUserId,
        Guid fileItemId,
        string newName,
        CancellationToken cancellationToken = default);

    Task<FileItem?> MoveAsync(
        Guid ownerUserId,
        Guid fileItemId,
        Guid? newParentFolderId,
        CancellationToken cancellationToken = default);

    // Reparent AND rename a file atomically (used by the photo organizer for
    // keep-both conflict resolution). DB-only — the blob and any FileThumbnail
    // rows are untouched. Throws FolderNotFoundException for an invalid target
    // and DuplicateFileNameException if (targetParentFolderId, finalName) is
    // already taken by another active sibling. Returns null if the file is
    // missing/foreign/deleted.
    Task<FileItem?> MoveToFolderAsync(
        Guid ownerUserId,
        Guid fileItemId,
        Guid? targetParentFolderId,
        string finalName,
        CancellationToken cancellationToken = default);

    // `reason` is the explicit delete intent. A deleted-content tombstone is
    // recorded ONLY for user-intent reasons (UserDelete/UserBulkDelete) AND only
    // when this was the owner's final active occurrence of the content. The
    // default (Unspecified) never records a tombstone — behaviour is never
    // inferred from the caller.
    Task<bool> SoftDeleteAsync(
        Guid ownerUserId,
        Guid fileItemId,
        CancellationToken cancellationToken = default,
        FileDeleteReason reason = FileDeleteReason.Unspecified);

    // Returns the restored FileItem, or null if no such file exists for this
    // owner (treat as 404). Restoring an already-active file is idempotent and
    // returns the file unchanged. Throws RestoreParentDeletedException when
    // the parent folder is itself soft-deleted, and DuplicateFileNameException
    // when an active sibling already occupies the file's slot.
    Task<FileItem?> RestoreAsync(
        Guid ownerUserId,
        Guid fileItemId,
        CancellationToken cancellationToken = default);

    // Permanently deletes a soft-deleted FileItem (mirrors a single tick of
    // FileItemSweeper.RunOnceAsync, but on demand and with no grace window).
    // Returns true on success, false when the file is missing or foreign
    // (caller maps to 404). Throws ResourceNotInTrashException when the file
    // is owned but currently active (caller maps to 409). Does not physically
    // delete blob files — BlobJanitor handles physical reclamation on its
    // after the separate physical-blob grace window expires.
    Task<bool> PermanentDeleteAsync(
        Guid ownerUserId,
        Guid fileItemId,
        CancellationToken cancellationToken = default);

    // Re-runs embedded image metadata extraction for one existing blob's
    // metadata row (slice 55 backfill). Idempotent: refreshes the typed fields
    // + raw document + ExtractionVersion. Returns false when no BlobMetadata
    // row exists for the blob. Operates on the blob (shared, content-derived),
    // not on any owner-scoped FileItem, and never mutates file bytes.
    Task<bool> ReExtractEmbeddedMetadataAsync(
        Guid blobObjectId,
        CancellationToken cancellationToken = default);

    // Probes one existing VIDEO blob's metadata row (ffprobe) and persists the
    // refreshed typed fields + dimensions + VideoExtractionVersion. Idempotent.
    // Returns false when no BlobMetadata row exists. Operates on the blob
    // (shared, content-derived), never mutates file bytes.
    Task<bool> ReExtractVideoMetadataAsync(
        Guid blobObjectId,
        CancellationToken cancellationToken = default);

    // Strong metadata mutation: strips embedded metadata (EXIF / IPTC / XMP /
    // ICC / format text) from an image FileItem (slice 58). The existing blob
    // is NEVER modified in place — re-encoded bytes go through the dedup-aware
    // IBlobService.StoreAsync, which either reuses an existing matching blob
    // or creates a new one with a new SHA-256. Only THIS FileItem is updated
    // to reference the new blob. Other FileItems sharing the old deduplicated
    // blob remain unchanged. User metadata (title / description / tags /
    // rating / favorite / overrides) is preserved.
    //
    // Returns the updated FileItem on success, or null when the file is
    // missing / foreign / soft-deleted (caller maps to 404). Throws
    // UnsupportedImageFormatException for non-image / unsupported formats
    // (caller maps to 415) and ImageProcessingLimitException when the image
    // exceeds the configured decoder caps (caller maps to 415).
    Task<Domain.FileItem?> StripEmbeddedMetadataAsync(
        Guid ownerUserId,
        Guid fileItemId,
        CancellationToken cancellationToken = default);

    // Slice 66: bakes the file's user DateTaken override into the image bytes
    // (EXIF DateTimeOriginal/Digitized). Strong mutation — same blob-immutable
    // semantics as StripEmbeddedMetadataAsync (new blob, caller-only repoint,
    // preserved user metadata, regenerated BlobMetadata + thumbnails). Returns
    // null for missing/foreign/soft-deleted (404). Throws
    // UnsupportedImageFormatException (415) for unsupported formats and
    // MetadataOperationInputMissingException (400) when no DateTaken override
    // is set on the file.
    Task<Domain.FileItem?> WriteDateTakenAsync(
        Guid ownerUserId,
        Guid fileItemId,
        CancellationToken cancellationToken = default);

    // Slice 66: opens a metadata-stripped READ stream of the file without
    // mutating the FileItem or creating a new blob. Owner-scoped; null for
    // missing/foreign/soft-deleted (404). Throws UnsupportedImageFormatException
    // (415) for non-strippable formats. The returned FileContent's stream is a
    // buffered in-memory copy the caller must dispose.
    Task<FileContent?> OpenPrivacySafeContentAsync(
        Guid ownerUserId,
        Guid fileItemId,
        CancellationToken cancellationToken = default);

    // Slice 75: returns all active FileItems owned by the same user that point
    // to the same underlying blob as the given fileItemId. The fileItemId is
    // used to find the blob server-side; the blob identity is never exposed.
    // Returns null when fileItemId is missing / foreign / soft-deleted (404).
    // The list always includes the requested fileItemId itself so the caller
    // gets a complete picture. Safe fields only — never SHA, BlobObjectId,
    // StorageKey, or raw metadata.
    Task<IReadOnlyList<DuplicateOccurrence>?> ListDuplicateOccurrencesAsync(
        Guid ownerUserId,
        Guid fileItemId,
        CancellationToken cancellationToken = default);
}
