// Reading back what the product actually sent.
//
// The ephemeral stack ships a local SMTP sink (Mailpit) that accepts every
// message and forwards none, so a browser test can follow a REAL reset link —
// generated by the real recovery flow, delivered over a real SMTP conversation
// — with no mail server and no possibility of reaching a real mailbox.

import { MAIL_URL } from './env';
import { waitFor } from './api';

interface MailpitSummary {
  readonly ID: string;
  readonly To: { Address: string }[];
  readonly Subject: string;
}

interface MailpitMessage {
  readonly ID: string;
  readonly Subject: string;
  readonly Text: string;
}

export async function clearMailbox(): Promise<void> {
  const response = await fetch(`${MAIL_URL}/api/v1/messages`, { method: 'DELETE' });
  if (!response.ok) {
    throw new Error(`could not clear the mail sink: ${response.status}`);
  }
}

async function listFor(address: string): Promise<MailpitSummary[]> {
  const response = await fetch(`${MAIL_URL}/api/v1/messages?limit=50`);
  if (!response.ok) {
    throw new Error(`could not list captured mail: ${response.status}`);
  }
  const body = (await response.json()) as { messages?: MailpitSummary[] };
  return (body.messages ?? []).filter((m) =>
    m.To.some((to) => to.Address.toLowerCase() === address.toLowerCase()));
}

/** Waits for a message to arrive for `address` and returns its plain-text body. */
export async function waitForMessage(address: string, timeoutMs = 20_000): Promise<MailpitMessage> {
  let found: MailpitSummary | undefined;
  await waitFor(
    `an email to ${address}`,
    async () => {
      const messages = await listFor(address);
      found = messages[0];
      return !!found;
    },
    timeoutMs,
    500,
  );

  const response = await fetch(`${MAIL_URL}/api/v1/message/${found!.ID}`);
  if (!response.ok) {
    throw new Error(`could not read the captured message: ${response.status}`);
  }
  return (await response.json()) as MailpitMessage;
}

/**
 * The raw token, taken out of the message exactly as a recipient would: from
 * the `#token=` fragment of the only link in the body.
 */
export function resetTokenFrom(message: MailpitMessage): string {
  const match = /#token=([^\s>"']+)/.exec(message.Text);
  if (!match) {
    throw new Error('the captured message contains no reset link');
  }
  return decodeURIComponent(match[1]);
}
