#!/usr/bin/env bash
# Gate 3A — reproducible native packaging for NubArca in-process OpenVINO.
#
# Obtains the pinned onnxruntime-openvino Linux wheel, verifies its COMPLETE
# SHA-256, extracts ONLY the required runtime + provider libraries, asserts the
# ABI/version assumptions, and writes a per-file manifest with hashes.
#
# It fails closed on: checksum mismatch, a missing required file, or a bundled
# OpenVINO/ORT version that differs from the lock. It never downloads "latest"
# and never copies files from a host or an external scratchpad.
#
# Usage: fetch-native-libs.sh <output-dir>   (default: ./native)
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
. "$here/onnxruntime-openvino.lock"

out="${1:-$here/native}"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# --- Required runtime libraries (and only these) --------------------------------
# Everything the ORT OpenVINO EP needs for CPU + GPU inference; the unrelated
# frontends (paddle/pytorch/tensorflow), AUTO/HETERO/MULTI, NPU and the C API are
# deliberately excluded. The build-time verifier exercises CPU (and GPU at run
# time) so an over-trimmed set fails the gate rather than shipping broken.
required_globs=(
  "libonnxruntime.so.${ORT_ABI_VERSION}"
  "libonnxruntime_providers_shared.so"
  "libonnxruntime_providers_openvino.so"
  "libopenvino.so*"
  "libopenvino_onnx_frontend.so*"     # direct NEEDED of providers_openvino.so
  "libopenvino_intel_cpu_plugin.so"   # dlopen'd for device_type=CPU
  "libopenvino_intel_gpu_plugin.so"   # dlopen'd for device_type=GPU
  "libtbb.so*"
  "libtbbmalloc.so*"
)

echo "[fetch] $WHEEL_FILENAME"
curl -fsSL -o "$work/pkg.whl" "$WHEEL_URL"

echo "[verify] sha256"
actual="$(sha256sum "$work/pkg.whl" | awk '{print $1}')"
if [ "$actual" != "$WHEEL_SHA256" ]; then
  echo "FATAL: checksum mismatch" >&2
  echo "  expected: $WHEEL_SHA256" >&2
  echo "  actual:   $actual" >&2
  exit 1
fi
echo "[verify] sha256 OK ($actual)"

echo "[extract] onnxruntime/capi/* -> staging"
unzip -o -q "$work/pkg.whl" 'onnxruntime/capi/*' -d "$work/ex"
capi="$work/ex/onnxruntime/capi"

rm -rf "$out"; mkdir -p "$out"
missing=0
for glob in "${required_globs[@]}"; do
  # shellcheck disable=SC2086
  matches=$(cd "$capi" && ls -1 $glob 2>/dev/null || true)
  if [ -z "$matches" ]; then
    echo "FATAL: required library not found in wheel: $glob" >&2
    missing=1; continue
  fi
  while IFS= read -r f; do cp -a "$capi/$f" "$out/$f"; done <<<"$matches"
done
[ "$missing" -eq 0 ] || { echo "FATAL: expected files differ from lock" >&2; exit 1; }

# --- ABI / version assertions ---------------------------------------------------
[ -f "$out/libonnxruntime.so.${ORT_ABI_VERSION}" ] \
  || { echo "FATAL: ORT ABI ${ORT_ABI_VERSION} core missing" >&2; exit 1; }
[ -f "$out/libopenvino.so.${OPENVINO_VERSION}" ] \
  || { echo "FATAL: bundled OpenVINO != ${OPENVINO_VERSION}" >&2; exit 1; }
echo "[verify] ORT core ${ORT_ABI_VERSION} + OpenVINO ${OPENVINO_VERSION} present"

# LICENSE + third-party notices for redistribution compliance (ORT MIT /
# OpenVINO + oneTBB Apache-2.0; the notices file enumerates bundled third parties).
mkdir -p "$out/licenses"
# Extract directly (no `| grep -q` guard — that trips pipefail via SIGPIPE).
unzip -o -q -j "$work/pkg.whl" onnxruntime/LICENSE onnxruntime/ThirdPartyNotices.txt \
  -d "$out/licenses" 2>/dev/null || true
[ -f "$out/licenses/LICENSE" ] || { echo "FATAL: wheel LICENSE not captured" >&2; exit 1; }

# --- Per-file manifest ----------------------------------------------------------
{
  echo "# Generated by fetch-native-libs.sh — do not edit."
  echo "ort_openvino_version=${ORT_OPENVINO_VERSION}"
  echo "openvino_version=${OPENVINO_VERSION}"
  echo "wheel_sha256=${WHEEL_SHA256}"
  echo "# sha256  file"
  (cd "$out" && find . -maxdepth 1 -type f -name '*.so*' | sort | while read -r f; do
     sha256sum "$f"; done)
} > "$out/NATIVE_MANIFEST.txt"

echo "[done] $(cd "$out" && ls -1 *.so* | wc -l) libraries -> $out"
