using System.Text.Json;
using NubArca.Api.Domain;
using NubArca.Api.Print;
using Xunit;

namespace NubArca.Api.Tests.Print;

/// <summary>
/// The server's framing against the shared table — the same file the browser's
/// contracts test reads, generated by a third, independent implementation. A
/// preview and a print that disagree are a guest composing one thing and
/// collecting another.
/// </summary>
public sealed class PhotoPlacementGeometryTests
{
    private static JsonElement Table()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "NubArca.sln"))) dir = dir.Parent;
        Assert.NotNull(dir);
        var path = Path.Combine(dir!.FullName, "packages", "contracts", "src", "photoPlacement.cases.json");
        return JsonDocument.Parse(File.ReadAllText(path)).RootElement;
    }

    private static void Close(double actual, double expected, string what) =>
        Assert.True(Math.Abs(actual - expected) < 1e-9, $"{what}: {actual} ≠ {expected}");

    [Fact]
    public void Every_Case_Of_The_Shared_Table_Exactly()
    {
        var table = Table();
        Assert.Equal(PhotoPlacementGeometry.MaxZoom, table.GetProperty("maxZoom").GetDouble());
        var cases = table.GetProperty("cases").EnumerateArray().ToList();
        Assert.True(cases.Count >= 300);
        foreach (var c in cases)
        {
            var photo = c.GetProperty("photoAspect").GetDouble();
            var frame = c.GetProperty("frameAspect").GetDouble();
            var p = c.GetProperty("placement");
            var placement = new PhotoPlacement(
                p.GetProperty("centerX").GetDouble(), p.GetProperty("centerY").GetDouble(), p.GetProperty("zoom").GetDouble());
            var id = $"{photo}/{frame}/{placement}";
            Close(PhotoPlacementGeometry.ContainZoom(photo, frame), c.GetProperty("containZoom").GetDouble(), $"{id} contain");

            var placed = PhotoPlacementGeometry.Place(photo, frame, placement);
            var visible = PhotoPlacementGeometry.Visible(placed);
            foreach (var (actual, name) in new[] { (placed, "placed"), (visible, "visible") })
            {
                var expected = c.GetProperty(name);
                Close(actual.Left, expected.GetProperty("left").GetDouble(), $"{id} {name}.left");
                Close(actual.Top, expected.GetProperty("top").GetDouble(), $"{id} {name}.top");
                Close(actual.Width, expected.GetProperty("width").GetDouble(), $"{id} {name}.width");
                Close(actual.Height, expected.GetProperty("height").GetDouble(), $"{id} {name}.height");
            }

            if (c.TryGetProperty("legacyCrop", out var legacy))
            {
                // zoom ≥ 1: exactly the crop every stored framing already meant.
                var crop = PhotoPlacementGeometry.LegacyCrop(placed);
                Close(crop.X, legacy.GetProperty("cropX").GetDouble(), $"{id} cropX");
                Close(crop.Y, legacy.GetProperty("cropY").GetDouble(), $"{id} cropY");
                Close(crop.Width, legacy.GetProperty("cropWidth").GetDouble(), $"{id} cropWidth");
                Close(crop.Height, legacy.GetProperty("cropHeight").GetDouble(), $"{id} cropHeight");
            }

            // Never stretched, never NaN.
            Assert.True(double.IsFinite(placed.Left) && double.IsFinite(placed.Width));
            Close(placed.Width * frame / placed.Height, photo, $"{id} aspect");
        }
    }

    [Fact]
    public void The_Guest_Book_Frames_Are_The_Clients_Frames()
    {
        foreach (var c in Table().GetProperty("guestbookTemplates").EnumerateArray())
        {
            Close(PartyGuestbookTemplates.FrameAspect(
                    c.GetProperty("key").GetString()!, c.GetProperty("version").GetInt32(),
                    c.GetProperty("photoAspect").GetDouble()),
                c.GetProperty("frameAspect").GetDouble(),
                $"{c.GetProperty("key").GetString()}@{c.GetProperty("version").GetInt32()}");
        }
    }

    [Theory]
    [InlineData(1.5, 2.0 / 3)]
    [InlineData(2.0 / 3, 1.5)]
    [InlineData(1, 1)]
    public void Zoom_Below_Contain_Is_Refused_And_A_Rounded_Contain_Is_Accepted(double photo, double frame)
    {
        var contain = PhotoPlacementGeometry.ContainZoom(photo, frame);
        Assert.True(PhotoPlacementGeometry.IsValid(photo, frame, new(0.5, 0.5, contain)));
        // A preview's aspect a fraction of a percent off is still "Adatta"…
        Assert.True(PhotoPlacementGeometry.IsValid(photo, frame, new(0.5, 0.5, contain * 0.995)));
        // …and drawn at contain, never smaller.
        Assert.Equal(PhotoPlacementGeometry.Place(photo, frame, new(0.5, 0.5, contain)),
            PhotoPlacementGeometry.Place(photo, frame, new(0.5, 0.5, contain * 0.995)));
        Assert.False(PhotoPlacementGeometry.IsValid(photo, frame, new(0.5, 0.5, contain * 0.9)));
        Assert.False(PhotoPlacementGeometry.IsValid(photo, frame, new(0.5, 0.5, 4.01)));
        Assert.False(PhotoPlacementGeometry.IsValid(photo, frame, new(-0.01, 0.5, 1)));
        Assert.False(PhotoPlacementGeometry.IsValid(photo, frame, new(0.5, double.NaN, 1)));
    }
}
