import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';
import {
  centerPlacement, containZoom, fillPlacement, fitPlacement, isValidPlacement, legacyCropOf,
  MAX_PLACEMENT_ZOOM, panPlacement, placePhoto, sliderMinimumZoom, visiblePhotoRect,
} from './photoPlacement.ts';

// The framing rules against the shared table — the same file the server's
// tests read, generated by a third, independent implementation.

interface Rect { left: number; top: number; width: number; height: number }
interface Case {
  photoAspect: number; frameAspect: number;
  placement: { centerX: number; centerY: number; zoom: number };
  containZoom: number; placed: Rect; visible: Rect;
  legacyCrop?: { cropX: number; cropY: number; cropWidth: number; cropHeight: number };
}
const table = JSON.parse(readFileSync(
  join(dirname(fileURLToPath(import.meta.url)), 'photoPlacement.cases.json'), 'utf8')) as { maxZoom: number; cases: Case[] };

const close = (actual: number, expected: number, what: string) =>
  assert.ok(Math.abs(actual - expected) < 1e-9, `${what}: ${actual} ≠ ${expected}`);

test('every case of the shared table, exactly', () => {
  assert.equal(table.maxZoom, MAX_PLACEMENT_ZOOM);
  assert.ok(table.cases.length >= 300);
  for (const c of table.cases) {
    const id = JSON.stringify([c.photoAspect, c.frameAspect, c.placement]);
    close(containZoom(c.photoAspect, c.frameAspect), c.containZoom, `${id} contain`);
    const placed = placePhoto(c.photoAspect, c.frameAspect, c.placement);
    for (const k of ['left', 'top', 'width', 'height'] as const) {
      close(placed[k], c.placed[k], `${id} placed.${k}`);
      close(visiblePhotoRect(placed)[k], c.visible[k], `${id} visible.${k}`);
    }
    if (c.legacyCrop) {
      // zoom ≥ 1: the very crop the framing meant before zooming out existed.
      const crop = legacyCropOf(placed);
      for (const k of ['cropX', 'cropY', 'cropWidth', 'cropHeight'] as const) close(crop[k], c.legacyCrop[k], `${id} ${k}`);
    }
  }
});

test('the invariants hold on every case', () => {
  for (const c of table.cases) {
    const placed = placePhoto(c.photoAspect, c.frameAspect, c.placement);
    for (const v of Object.values(placed)) assert.ok(Number.isFinite(v));
    // The photograph is never stretched.
    close((placed.width * c.frameAspect) / placed.height, c.photoAspect, 'aspect');
    // An axis on which it is smaller than the frame is centred.
    if (placed.width < 1) close(placed.left, (1 - placed.width) / 2, 'centred x');
    if (placed.height < 1) close(placed.top, (1 - placed.height) / 2, 'centred y');
    // An axis on which it overflows never shows a gap.
    if (placed.width >= 1) assert.ok(placed.left <= 1e-12 && placed.left + placed.width >= 1 - 1e-12);
    if (placed.height >= 1) assert.ok(placed.top <= 1e-12 && placed.top + placed.height >= 1 - 1e-12);
  }
});

test('contain shows the whole photograph, and no more empty frame than it must', () => {
  for (const [photo, frame] of [[1.5, 0.667], [0.667, 1.5], [1, 1], [2, 1], [0.5, 1.5]]) {
    const placed = placePhoto(photo, frame, fitPlacement(photo, frame));
    const visible = visiblePhotoRect(placed);
    close(visible.width * visible.height, placed.width * placed.height, 'all of it visible');
    // Touches the frame on one axis: zooming out further would only add bands.
    assert.ok(Math.abs(placed.width - 1) < 1e-9 || Math.abs(placed.height - 1) < 1e-9);
    // Below contain is drawn at contain, and refused as a framing.
    assert.deepEqual(placePhoto(photo, frame, { centerX: 0.5, centerY: 0.5, zoom: 0.01 }), placed);
    assert.equal(isValidPlacement(photo, frame, { centerX: 0.5, centerY: 0.5, zoom: containZoom(photo, frame) * 0.9 }), false);
  }
});

test('the buttons and the slider', () => {
  assert.deepEqual(fillPlacement(), { centerX: 0.5, centerY: 0.5, zoom: 1 });
  assert.deepEqual(fitPlacement(1.5, 2 / 3), { centerX: 0.5, centerY: 0.5, zoom: containZoom(1.5, 2 / 3) });
  assert.deepEqual(centerPlacement({ centerX: 0.1, centerY: 0.9, zoom: 2.5 }), { centerX: 0.5, centerY: 0.5, zoom: 2.5 });
  // The slider starts on its step at or above contain; "Adatta" reaches contain exactly.
  close(sliderMinimumZoom(1.5, 2 / 3), 0.45, 'slider min');
  assert.equal(sliderMinimumZoom(1, 1), 1);
  assert.ok(sliderMinimumZoom(2, 1) >= containZoom(2, 1));
});

test('a drag moves only an axis that overflows, and never past an edge', () => {
  // Zoomed out on a wide photograph in a tall frame: the height is underfilled.
  const start = { centerX: 0.5, centerY: 0.5, zoom: 0.8 };
  const moved = panPlacement(1.5, 2 / 3, start, 0.3, 0.3);
  assert.equal(moved.centerY, 0.5);
  assert.ok(moved.centerX < 0.5);
  // Dragged far right, it stops where the left edge meets the frame…
  const far = panPlacement(1.5, 2 / 3, start, 10, 0);
  close(placePhoto(1.5, 2 / 3, far).left, 0, 'held at the edge');
  // …and the first step back moves it at once.
  assert.ok(panPlacement(1.5, 2 / 3, far, -0.01, 0).centerX > far.centerX);
});

test('nonsense is drawn safely and refused as a framing', () => {
  for (const zoom of [Number.NaN, Number.POSITIVE_INFINITY, -1, 5]) {
    assert.equal(isValidPlacement(1.5, 1, { centerX: 0.5, centerY: 0.5, zoom }), false);
    for (const v of Object.values(placePhoto(1.5, 1, { centerX: 0.5, centerY: 0.5, zoom }))) assert.ok(Number.isFinite(v));
  }
  assert.equal(isValidPlacement(1.5, 1, { centerX: -0.1, centerY: 0.5, zoom: 1 }), false);
  for (const v of Object.values(placePhoto(Number.NaN, 0, { centerX: 0.5, centerY: 0.5, zoom: 1 }))) assert.ok(Number.isFinite(v));
});
