import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';
import {
  PRINT_LAYOUTS, arrangeSheet, layoutAllowed, layoutPhotoCounts, layoutSupportsStyle, slotAspect,
  type PrintLayout, type PrintPaper, type PrintRect, type PrintStyle,
} from './printLayouts.ts';

// The print catalogue against the shared table — the same file the server's
// catalogue (PrintLayouts.cs) is held to, generated by a third, independent
// implementation.

interface Case {
  layout: PrintLayout; style: PrintStyle; paper: PrintPaper; portrait: boolean;
  sheet: { width: number; height: number };
  slots: PrintRect[]; bands: PrintRect[]; slotAspect: number;
}
const table = JSON.parse(readFileSync(
  join(dirname(fileURLToPath(import.meta.url)), 'printLayouts.cases.json'), 'utf8')) as {
  cases: Case[];
  photoCounts: Record<PrintLayout, number[]>;
  allowed: { layout: PrintLayout; paper: PrintPaper; allowed: boolean }[];
  styles: { layout: PrintLayout; style: PrintStyle; supported: boolean }[];
};

const close = (actual: number, expected: number, what: string) =>
  assert.ok(Math.abs(actual - expected) < 1e-12, `${what}: ${actual} ≠ ${expected}`);

const sameRects = (actual: PrintRect[], expected: PrintRect[], what: string) => {
  assert.equal(actual.length, expected.length, `${what} count`);
  actual.forEach((rect, i) => {
    for (const k of ['x', 'y', 'width', 'height'] as const) close(rect[k], expected[i][k], `${what}[${i}].${k}`);
  });
};

test('every sheet of the shared table, exactly', () => {
  assert.ok(table.cases.length >= 20);
  for (const c of table.cases) {
    const id = `${c.layout}/${c.style}/${c.paper}/${c.portrait ? 'portrait' : 'landscape'}`;
    const sheet = arrangeSheet(c.layout, c.style, c.paper, c.portrait);
    assert.equal(sheet.width, c.sheet.width, `${id} width`);
    assert.equal(sheet.height, c.sheet.height, `${id} height`);
    sameRects(sheet.slots, c.slots, `${id} slots`);
    sameRects(sheet.bands, c.bands, `${id} bands`);
    close(slotAspect(c.layout, c.style, c.paper, c.portrait), c.slotAspect, `${id} slotAspect`);
  }
});

test('which paper makes what, how many photographs, and which style', () => {
  for (const row of table.allowed) assert.equal(layoutAllowed(row.paper, row.layout), row.allowed);
  for (const row of table.styles) assert.equal(layoutSupportsStyle(row.layout, row.style), row.supported);
  assert.deepEqual(Object.keys(table.photoCounts), [...PRINT_LAYOUTS]);
  for (const layout of PRINT_LAYOUTS) assert.deepEqual([...layoutPhotoCounts(layout)], table.photoCounts[layout]);
});
