import { describe, expect, it } from 'vitest';
import {
  MAX_USEFUL_DPR,
  type LevelLike,
  type PlaybackDisplayContext,
  levelsBySize,
  prefersLowestLevel,
  selectInitialLevel,
} from './hlsLevelSelection';

// The REAL ladder, transcribed from a master playlist generated by running the
// production ffmpeg argument shape (FfmpegVideoHlsTranscoder.BuildArguments)
// against a 1920x1080 H.264 source. Note the order: ffmpeg's -var_stream_map is
// "v:0,a:0,name:high v:1,a:1,name:low", so the HIGHEST rendition is listed
// FIRST. Every test here keeps that order, because production has it.
const LANDSCAPE_LADDER: LevelLike[] = [
  { width: 1920, height: 1080, bitrate: 15591006 },
  { width: 854, height: 480, bitrate: 468654 },
];
const HIGH = 0;
const LOW = 1;

// Same generator, 1080x1920 portrait source. The short side is what gets
// capped, so the high rung keeps full resolution and the low rung is 480 WIDE.
const PORTRAIT_LADDER: LevelLike[] = [
  { width: 1080, height: 1920, bitrate: 15700636 },
  { width: 480, height: 854, bitrate: 496138 },
];

// A deeper synthetic ladder, to prove the policy does not merely pick "the
// other one" in a two-rung list.
const THREE_RUNG: LevelLike[] = [
  { width: 1920, height: 1080, bitrate: 5_000_000 },
  { width: 854, height: 480, bitrate: 1_000_000 },
  { width: 1280, height: 720, bitrate: 2_500_000 },
];
const RUNG_1080 = 0;
const RUNG_480 = 1;
const RUNG_720 = 2;

function ctx(over: Partial<PlaybackDisplayContext> = {}): PlaybackDisplayContext {
  return {
    playerWidth: 1280,
    playerHeight: 720,
    viewportWidth: 1280,
    viewportHeight: 720,
    expectsFullscreen: true,
    devicePixelRatio: 1,
    saveData: false,
    effectiveType: null,
    ...over,
  };
}

describe('level ordering', () => {
  it('sorts by pixel count, never by playlist order', () => {
    // The generated master lists high first; ascending order must not.
    expect(levelsBySize(LANDSCAPE_LADDER)).toEqual([LOW, HIGH]);
    expect(levelsBySize(THREE_RUNG)).toEqual([RUNG_480, RUNG_720, RUNG_1080]);
  });

  it('breaks pixel ties on bitrate', () => {
    const tied: LevelLike[] = [
      { width: 854, height: 480, bitrate: 900_000 },
      { width: 854, height: 480, bitrate: 400_000 },
    ];
    expect(levelsBySize(tied)).toEqual([1, 0]);
  });
});

describe('selectInitialLevel — display size', () => {
  it('starts at 480p on a small player', () => {
    // A 640x360 box at 1x needs ~360 lines; the low rung covers it.
    expect(selectInitialLevel(LANDSCAPE_LADDER, ctx({
      playerWidth: 640, playerHeight: 360, viewportWidth: 640, viewportHeight: 360,
    }))).toBe(LOW);
  });

  it('starts at the high rung on a large desktop', () => {
    expect(selectInitialLevel(LANDSCAPE_LADDER, ctx({
      playerWidth: 2560, playerHeight: 1440, viewportWidth: 2560, viewportHeight: 1440,
    }))).toBe(HIGH);
  });

  it('never picks a level higher than the player can show', () => {
    // 1280x720 at 1x: the 720 rung covers it exactly, so 1080 is waste.
    expect(selectInitialLevel(THREE_RUNG, ctx({
      playerWidth: 1280, playerHeight: 720, viewportWidth: 1280, viewportHeight: 720,
    }))).toBe(RUNG_720);
  });

  it('picks the smallest rendition that still covers the target', () => {
    // Just under the 720 rung's height: 480 is not enough, 720 is, 1080 is waste.
    expect(selectInitialLevel(THREE_RUNG, ctx({
      playerWidth: 1200, playerHeight: 675, viewportWidth: 1200, viewportHeight: 675,
    }))).toBe(RUNG_720);
  });

  it('returns the best available when nothing covers the display', () => {
    expect(selectInitialLevel(LANDSCAPE_LADDER, ctx({
      playerWidth: 3840, playerHeight: 2160, viewportWidth: 3840, viewportHeight: 2160,
    }))).toBe(HIGH);
  });

  it('gives hls.js the decision when there is no laid-out box', () => {
    expect(selectInitialLevel(LANDSCAPE_LADDER, ctx({
      playerWidth: 0, playerHeight: 0, viewportWidth: 0, viewportHeight: 0,
    }))).toBe(-1);
  });

  it('has nothing to choose from an empty ladder', () => {
    expect(selectInitialLevel([], ctx())).toBe(-1);
  });
});

describe('selectInitialLevel — device pixel ratio', () => {
  it('asks for more lines on a 2x display', () => {
    const box = { playerWidth: 640, playerHeight: 360, viewportWidth: 640, viewportHeight: 360 };
    expect(selectInitialLevel(THREE_RUNG, ctx({ ...box, devicePixelRatio: 1 }))).toBe(RUNG_480);
    expect(selectInitialLevel(THREE_RUNG, ctx({ ...box, devicePixelRatio: 2 }))).toBe(RUNG_720);
  });

  it('caps the ratio, so a 3x phone does not demand the top rung for nothing', () => {
    const box = { playerWidth: 640, playerHeight: 360, viewportWidth: 640, viewportHeight: 360 };
    const atCap = selectInitialLevel(THREE_RUNG, ctx({ ...box, devicePixelRatio: MAX_USEFUL_DPR }));
    expect(selectInitialLevel(THREE_RUNG, ctx({ ...box, devicePixelRatio: 4 }))).toBe(atCap);
  });

  it('treats a nonsense ratio as 1x rather than propagating it', () => {
    const box = { playerWidth: 640, playerHeight: 360, viewportWidth: 640, viewportHeight: 360 };
    expect(selectInitialLevel(THREE_RUNG, ctx({ ...box, devicePixelRatio: 0 }))).toBe(RUNG_480);
    expect(selectInitialLevel(THREE_RUNG, ctx({ ...box, devicePixelRatio: Number.NaN }))).toBe(RUNG_480);
  });
});

describe('selectInitialLevel — orientation', () => {
  it('fits portrait levels by width in a portrait viewport', () => {
    // 390x844 at 2x: the portrait low rung (480x854) cannot cover the fitted
    // picture, so the high rung is correct — and the maths must not have used
    // "height" as a stand-in for "short side".
    expect(selectInitialLevel(PORTRAIT_LADDER, ctx({
      playerWidth: 390, playerHeight: 844, viewportWidth: 390, viewportHeight: 844,
      devicePixelRatio: 3,
    }))).toBe(0);
  });

  it('bounds a portrait level in a landscape box by HEIGHT, not width', () => {
    // A portrait video in a 1920x1080 box is pillarboxed: it fills the 1080
    // lines and uses ~607px of width. So it needs 1080 source lines, and the
    // 854-line low rung does not cover it — the high rung is right.
    // Width-based reasoning would see 607 << 480-rung-is-fine and start soft.
    expect(selectInitialLevel(PORTRAIT_LADDER, ctx({
      playerWidth: 1920, playerHeight: 1080, viewportWidth: 1920, viewportHeight: 1080,
    }))).toBe(0);
    // Shrink the box below the low rung's 854 lines and it becomes enough.
    expect(selectInitialLevel(PORTRAIT_LADDER, ctx({
      playerWidth: 1920, playerHeight: 800, viewportWidth: 1920, viewportHeight: 800,
    }))).toBe(1);
  });
});

describe('selectInitialLevel — fullscreen projection', () => {
  it('sizes for the fullscreen viewport when the player goes fullscreen on play', () => {
    // A small windowed box on a large screen. Sizing for the box alone would
    // start at 480p and only climb after the fullscreen transition.
    expect(selectInitialLevel(LANDSCAPE_LADDER, ctx({
      playerWidth: 480, playerHeight: 270,
      viewportWidth: 2560, viewportHeight: 1440,
      expectsFullscreen: true,
    }))).toBe(HIGH);
  });

  // The waste this flag exists to prevent. capLevelToPlayerSize does NOT clamp
  // the first fragment — level-controller uses hls.startLevel verbatim and
  // bounds it only by levels.length - 1 — so an over-ambitious start level is
  // one oversized segment actually downloaded before ABR walks it back.
  it('sizes for the BOX when the player stays embedded', () => {
    expect(selectInitialLevel(LANDSCAPE_LADDER, ctx({
      playerWidth: 480, playerHeight: 270,
      viewportWidth: 2560, viewportHeight: 1440,
      expectsFullscreen: false,
    }))).toBe(LOW);
  });

  it('never projects for an embedded player, at any viewport size', () => {
    for (const [vw, vh] of [[1440, 900], [1920, 1080], [2560, 1440], [3840, 2160]]) {
      expect(selectInitialLevel(THREE_RUNG, ctx({
        playerWidth: 640, playerHeight: 360,
        viewportWidth: vw, viewportHeight: vh,
        expectsFullscreen: false,
      })), `${vw}x${vh}`).toBe(RUNG_480);
    }
  });

  it('uses the player box when it is the larger of the two', () => {
    expect(selectInitialLevel(THREE_RUNG, ctx({
      playerWidth: 1920, playerHeight: 1080,
      viewportWidth: 640, viewportHeight: 360,
    }))).toBe(RUNG_1080);
  });
});

describe('selectInitialLevel — connection', () => {
  it('starts at the bottom when the user asked to save data', () => {
    expect(selectInitialLevel(LANDSCAPE_LADDER, ctx({
      playerWidth: 2560, playerHeight: 1440, viewportWidth: 2560, viewportHeight: 1440,
      saveData: true,
    }))).toBe(LOW);
  });

  it('starts at the bottom on a slow effective connection', () => {
    for (const effectiveType of ['slow-2g', '2g', '3g']) {
      expect(selectInitialLevel(LANDSCAPE_LADDER, ctx({
        playerWidth: 2560, playerHeight: 1440, viewportWidth: 2560, viewportHeight: 1440,
        effectiveType,
      })), effectiveType).toBe(LOW);
    }
  });

  it('treats 4g as normal', () => {
    expect(prefersLowestLevel(ctx({ effectiveType: '4g' }))).toBe(false);
  });

  it('treats a MISSING Network Information API as normal, not as slow', () => {
    // Most browsers do not ship navigator.connection. Absent evidence of a
    // slow link is not evidence of one — the old behaviour would have punished
    // every Firefox and Safari user with the low rung.
    expect(prefersLowestLevel(ctx({ effectiveType: null, saveData: false }))).toBe(false);
    expect(prefersLowestLevel(ctx({ effectiveType: undefined, saveData: false }))).toBe(false);
    expect(selectInitialLevel(LANDSCAPE_LADDER, ctx({
      playerWidth: 2560, playerHeight: 1440, viewportWidth: 2560, viewportHeight: 1440,
      effectiveType: null,
    }))).toBe(HIGH);
  });
});

describe('selectInitialLevel — playlist order independence', () => {
  it('gives the same answer whatever order the levels arrive in', () => {
    const display = ctx({
      playerWidth: 1280, playerHeight: 720, viewportWidth: 1280, viewportHeight: 720,
    });
    const ascending = [THREE_RUNG[RUNG_480], THREE_RUNG[RUNG_720], THREE_RUNG[RUNG_1080]];
    const shuffled = [THREE_RUNG[RUNG_720], THREE_RUNG[RUNG_1080], THREE_RUNG[RUNG_480]];

    // Same LEVEL in every arrangement, even though its index moves.
    expect(ascending[selectInitialLevel(ascending, display)]).toEqual(THREE_RUNG[RUNG_720]);
    expect(shuffled[selectInitialLevel(shuffled, display)]).toEqual(THREE_RUNG[RUNG_720]);
    expect(THREE_RUNG[selectInitialLevel(THREE_RUNG, display)]).toEqual(THREE_RUNG[RUNG_720]);
  });
});
